services:
  discord_bot:
    image: ghcr.io/${REPO_OWNER:-pesu-dev}/${DOCKER_IMAGE_NAME:-discord_bot}:${IMAGE_TAG:-dev}
    container_name: discord_bot_${TARGET_ENV:-local}
    restart: always
    env_file:
      - ${ENV_FILE:-.env}