name: PR Image Build

on:
  pull_request:
    branches:
      - dev

jobs:
  build_image:
    name: Build image (no push)
    uses: ./.github/workflows/build_and_push_image.yml
    with:
      image_tag: sha_${{ github.event.pull_request.head.sha }}
      push: false
